version: "3.8"
services:
    db:
        image: mysql:5.7
        container_name: db
        restart: always
        tty: true
        volumes:
          - ./mysql/data:/var/lib/mysql
          - ./mysql/script:/docker-entrypoint-initdb.d/
        environment:
          - MYSQL_DATABASE=nodedb
          - MYSQL_ROOT_PASSWORD=root
        command: --innodb-use-native-aio=0
        networks:
          - node-network
    nodeserver:
        build:
            context: ./node
        container_name: nodeserver
        ports:
            - "3000:3000"
        depends_on:
          - db
        networks:
          - node-network
    nginx:
        container_name: nginx
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"
        networks:
          - node-network
networks:
  node-network:
    driver: bridge